import React from "react";
import Head from "next/head";
import DashboardLayout from "@/components/dashboardLayout";
import { useRouter } from "next/router";
import InvoiceView from "@/components/invoiceView";

const InvoiceViewPage = () => {
  const router = useRouter();

  return (
    <>
      <Head>
        <title>Stock View</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <DashboardLayout>
          <InvoiceView />
        </DashboardLayout>
      </div>
    </>
  );
};

export default InvoiceViewPage;
